SELECT * From Movies
WHERE CategoryId IS NULL OR CinemaId IS NULL 

UPDATE Movies
SET CategoryId = 1
WHERE CategoryId IS NULL

UPDATE Movies
SET CinemaId = 1
WHERE CinemaId IS NULL

ALTER TABLE Movies
ALTER COLUMN CategoryId INT NOT NULL

ALTER TABLE Movies
ALTER COLUMN CinemaId INT NOT NULL

UPDATE Movies